name: build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    uses: bzimmer/actions/.github/workflows/build.yaml@main
    with:
      skipBuild: true
      skipCoverage: false
    secrets: inherit

  vuln:
    uses: bzimmer/actions/.github/workflows/vuln.yaml@main
